# Generated by Django 5.0.8 on 2024-10-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_image_description_alter_recipe_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='instruction_text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='instruction',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
