# Generated by Django 5.0.8 on 2024-10-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipephoto_recipe_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
