# Generated by Django 5.0.8 on 2024-10-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_rename_average_rating_recipe_calculated_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recipe.ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.ManyToManyField(related_name='recipes', to='recipe.instruction'),
        ),
    ]
